/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAmistosoRouteImport } from './routes/_authenticated/amistoso'
import { Route as AuthenticatedOnlineRouteImport } from './routes/_authenticated/online'
import { Route as AuthenticatedRetroRouteImport } from './routes/_authenticated/retro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAmistosoRoute = AuthenticatedAmistosoRouteImport.update({
  id: '/amistoso',
  path: '/amistoso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnlineRoute = AuthenticatedOnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetroRoute = AuthenticatedRetroRouteImport.update({
  id: '/retro',
  path: '/retro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/amistoso': typeof AuthenticatedAmistosoRoute
  '/online': typeof AuthenticatedOnlineRoute
  '/retro': typeof AuthenticatedRetroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/amistoso': typeof AuthenticatedAmistosoRoute
  '/online': typeof AuthenticatedOnlineRoute
  '/retro': typeof AuthenticatedRetroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/amistoso': typeof AuthenticatedAmistosoRoute
  '/_authenticated/online': typeof AuthenticatedOnlineRoute
  '/_authenticated/retro': typeof AuthenticatedRetroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/amistoso' | '/online' | '/retro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/amistoso' | '/online' | '/retro'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/amistoso'
    | '/_authenticated/online'
    | '/_authenticated/retro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/amistoso': {
      id: '/_authenticated/amistoso'
      path: '/amistoso'
      fullPath: '/amistoso'
      preLoaderRoute: typeof AuthenticatedAmistosoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/online': {
      id: '/_authenticated/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof AuthenticatedOnlineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retro': {
      id: '/_authenticated/retro'
      path: '/retro'
      fullPath: '/retro'
      preLoaderRoute: typeof AuthenticatedRetroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAmistosoRoute: typeof AuthenticatedAmistosoRoute
  AuthenticatedOnlineRoute: typeof AuthenticatedOnlineRoute
  AuthenticatedRetroRoute: typeof AuthenticatedRetroRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAmistosoRoute: AuthenticatedAmistosoRoute,
  AuthenticatedOnlineRoute: AuthenticatedOnlineRoute,
  AuthenticatedRetroRoute: AuthenticatedRetroRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
