/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as BrioRouteImport } from './routes/brio'
import { Route as CidadelaRouteImport } from './routes/cidadela'
import { Route as CorretorRouteImport } from './routes/corretor'
import { Route as GeradorRouteImport } from './routes/gerador'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const BrioRoute = BrioRouteImport.update({
  id: '/brio',
  path: '/brio',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadelaRoute = CidadelaRouteImport.update({
  id: '/cidadela',
  path: '/cidadela',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorRoute = CorretorRouteImport.update({
  id: '/corretor',
  path: '/corretor',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorRoute = GeradorRouteImport.update({
  id: '/gerador',
  path: '/gerador',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/brio': typeof BrioRoute
  '/cidadela': typeof CidadelaRoute
  '/corretor': typeof CorretorRoute
  '/gerador': typeof GeradorRoute
  '/noticias': typeof NoticiasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/brio': typeof BrioRoute
  '/cidadela': typeof CidadelaRoute
  '/corretor': typeof CorretorRoute
  '/gerador': typeof GeradorRoute
  '/noticias': typeof NoticiasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/brio': typeof BrioRoute
  '/cidadela': typeof CidadelaRoute
  '/corretor': typeof CorretorRoute
  '/gerador': typeof GeradorRoute
  '/noticias': typeof NoticiasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/brio'
    | '/cidadela'
    | '/corretor'
    | '/gerador'
    | '/noticias'
    | '/privacidade'
    | '/termos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/brio'
    | '/cidadela'
    | '/corretor'
    | '/gerador'
    | '/noticias'
    | '/privacidade'
    | '/termos'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/brio'
    | '/cidadela'
    | '/corretor'
    | '/gerador'
    | '/noticias'
    | '/privacidade'
    | '/termos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  BrioRoute: typeof BrioRoute
  CidadelaRoute: typeof CidadelaRoute
  CorretorRoute: typeof CorretorRoute
  GeradorRoute: typeof GeradorRoute
  NoticiasRoute: typeof NoticiasRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brio': {
      id: '/brio'
      path: '/brio'
      fullPath: '/brio'
      preLoaderRoute: typeof BrioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidadela': {
      id: '/cidadela'
      path: '/cidadela'
      fullPath: '/cidadela'
      preLoaderRoute: typeof CidadelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor': {
      id: '/corretor'
      path: '/corretor'
      fullPath: '/corretor'
      preLoaderRoute: typeof CorretorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador': {
      id: '/gerador'
      path: '/gerador'
      fullPath: '/gerador'
      preLoaderRoute: typeof GeradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  BrioRoute: BrioRoute,
  CidadelaRoute: CidadelaRoute,
  CorretorRoute: CorretorRoute,
  GeradorRoute: GeradorRoute,
  NoticiasRoute: NoticiasRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
